version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Xamarin.UITest
    versions:
    - 3.0.13
    - 3.0.14
    - 3.0.15
    - 3.0.16
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
